language: elixir

elixir:
  - 1.5
  - 1.6

otp_release:
  - 19.3
  - 20.3

env:
  - EXHAL_POISON_VERSION="~> 2.2"
  - EXHAL_POISON_VERSION="~> 3.1"
  - EXHAL_HTTPOISON_VERSION="~> 0.11"
  - EXHAL_HTTPOISON_VERSION="~> 1.0"

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 20.0
